### ISSUE TITLE
SuperEasy Issue: Typo on "Closed Crossroads"

### ISSUE THREAD

**Issue by maxwellll** [codecombat/codecombat#4624]
### Tasks
- [ ] In the //instructions it says "        // then use buildXY with buildType, x, and ythen use buildXY with buildType, x, and y"
- [ ] Change to "        // then use buildXY with buildType, x, and then use buildXY with buildType, x, and y

### Definition of Done
- [ ] Typo is corrected

### Assets
[Closed Crossroads](https://codecombat.com/play/level/closed-crossroad?)

**Comment by Bryukh** [comment]
Could you show where you found this typo? A screenshot would be nice. I can't find this text.

**Comment by Bryukh** [comment]
It was a redundant template for comments. Thanks. Fixed.
