### ISSUE TITLE
Checklist: Illia development phases

### ISSUE THREAD

**Issue by Chaboi45** [codecombat/codecombat#5951]
TODO
- [x] Make some small changes to abilities as needed. Visuals, balancing, small tweaks.
- [x] Select a few people from the forum to help test out Illia. (Using a specified private level to "sandbox" with Illia)
- [x] Get feedback and change abilities, if needed.
- [x] Do final changes
- [x] Tease Illia's abilities on #announcements on forum. (Add ability description and create GIFS of gameplay. )
- [x] Before releasing Illia, I will retest on other levels using Illia
- [x] <del>Important: Replace Ritic's teaser when you first go on CoCo with Illia's teaser. Instead of clicking to break ice, maybe something like a shadow revealing itself? Also add the GIFS there</del>
- [x] Release publicly.

**Comment by Chaboi45** [comment]
Released: https://discourse.codecombat.com/t/illia-is-released/24528
